version: '3.9'

services:
  db:
    image: postgres:15
    container_name: dapmeet-db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dapuser
      POSTGRES_PASSWORD: dappass
      POSTGRES_DB: dapmeet
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: dapmeet-backend
    command: uvicorn dapmeet.cmd.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata: {}