version: '3.9'

services:
  db-dev:
    image: postgres:15
    container_name: dapmeet-db-dev
    restart: always
    networks:
      - backend_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dapuser
      POSTGRES_PASSWORD: dappass
      POSTGRES_DB: dapmeet
    ports:
      - "55532:5432"

  backend-dev:
    build: .
    container_name: dapmeet-backend-dev
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - backend_network
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db-dev
    env_file:
      - .env

networks:
  backend_network:

volumes:
  pgdata: {}
