"""rm unique_constraint

Revision ID: e4d47d896c3c
Revises: 
Create Date: 2025-08-04 10:18:35.701816+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4d47d896c3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_chat_messages_created_at'))
        batch_op.drop_index(batch_op.f('idx_chat_messages_session_created'))
        batch_op.drop_index(batch_op.f('idx_chat_messages_session_id'))

    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uix_segment_session_speaker_ts_ver'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uix_segment_session_speaker_ts_ver'), ['session_id', 'google_meet_user_id', 'timestamp', 'version', 'message_id'])

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_chat_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_chat_messages_session_created'), ['session_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_chat_messages_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
