""".

Revision ID: 8192efe18eb5
Revises: 59aa9ed82df2
Create Date: 2025-07-29 07:15:22.308951+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8192efe18eb5'
down_revision: Union[str, None] = '59aa9ed82df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.drop_column('message')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('content')
        batch_op.drop_column('sender')

    # ### end Alembic commands ###
