"""upd meeting model

Revision ID: 8cbbf2532345
Revises: ff7213e3790f
Create Date: 2025-07-21 16:48:07.585531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbbf2532345'
down_revision: Union[str, None] = 'ff7213e3790f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_url_meet', type_='unique')
        batch_op.create_unique_constraint('uq_user_url_meet', ['user_id'])
        batch_op.drop_column('url_meet_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_meet_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint('uq_user_url_meet', type_='unique')
        batch_op.create_unique_constraint('uq_user_url_meet', ['user_id', 'url_meet_id'])

    # ### end Alembic commands ###
