"""create_all_missing_tables

Revision ID: f1d8a951e28d
Revises: 73cfc96116d0
Create Date: 2025-06-21 12:43:57.221325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d8a951e28d'
down_revision: Union[str, None] = '73cfc96116d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_segments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_segments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_segments_meeting_id'), ['meeting_id'], unique=False)

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('transcript')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_segments_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_transcript_segments_id'))
        batch_op.drop_index(batch_op.f('ix_transcript_segments_created_at'))

    op.drop_table('transcript_segments')
    # ### end Alembic commands ###
